// export-examples/vue/src/components/Add-Grocery.vue
<template>
  <div class="add-grocery">
    <input
      type="text"
      placeholder="Grocery"
      aria-label="Add a grocery item"
      v-model="item"
      @keydown.enter="addItem"
    />
  </div>
</template>

<script>
export default {
  name: 'Add-Grocery',
  data: () => {
    return {
      item: ''
    };
  },
  methods: {
    addItem: function() {
      this.$emit('grocery-added', this.item);
      this.item = '';
    }
  }
};
</script>

<style scoped lang="scss">
.add-grocery {
  display: flex;
  justify-content: center;
}

input {
  display: flex;
  flex: 0 0 75%;
  font-size: 1.5rem;
  padding: 10px 15px;
  border: 1px solid #420846;
  color: #07531b;

  &::placeholder {
    color: #07531b;
  }
}
</style>

// sample-apps/react/src/AddGrocery/AddGrocery.js
import React from 'react';

import './AddGrocery.css';

function AddGrocery(props) {
  const addItem = event => {
    if (event.key === 'Enter') {
      props.addItem(event.target.value);
      event.target.value = '';
    }
  };

  return (
    <div className="AddGrocery">
      <input
        type="text"
        placeholder="Grocery"
        aria-label="Add a grocery item"
        onKeyDown={addItem}
      />
    </div>
  );
}

export default AddGrocery;
