// 01-sample-apps/vue/src/App.vue
<template>
  <div id="app">
    <Title text="Vue Groceries" />
    <div class="scrollable-area">
      <div class="add-grocery">
        <Add-Grocery @groceryAdded="groceryAdded" />
      </div>
      <div class="grocery-list">
        <Grocery-List :items="groceryItems" @itemClicked="groceryItemClicked" />
      </div>
    </div>
  </div>
</template>

<script>
import Title from './components/Title.vue';
import AddGrocery from './components/Add-Grocery.vue';
import GroceryList from './components/Grocery-List.vue';
import { DataService } from './data.service';

export default {
  name: 'app',
  components: {
    Title,
    AddGrocery,
    GroceryList
  },
  data: () => {
    return {
      dataService: new DataService()
    };
  },
  computed: {
    groceryItems: function() {
      return this.dataService.items;
    }
  },
  methods: {
    groceryAdded: function(item) {
      this.dataService.addItem(item);
    },
    groceryItemClicked: function(item) {
      this.dataService.toggleItemStatus(item);
    }
  }
};
</script>

<style lang="scss">
html,
body {
  height: 100%;
  width: 100%;
  margin: 0;
  padding: 0;
  font-family: sans-serif;
  overflow: hidden;
}

#app {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: #b0dfbc;
  overflow: hidden;
}

.scrollable-area {
  display: block;
  flex: 1 1 auto;
  overflow: auto;

  .add-grocery {
    margin-top: 2rem;
  }

  .grocery-list {
    margin-top: 2rem;
  }
}
</style>

// 03-using-exported-components/react-based/src/App.js
import React, { useState, useRef, useEffect } from 'react';

import './App.css';
import { DataService } from './data.service';

const dataService = new DataService();

function App() {
  const [items, setItems] = useState(dataService.items);

  // groceryAdded
  let addGrocery = useRef(null);
  useEffect(() => {
    // groceryAdded handler
    const element = addGrocery.current;
    let handler = data => {
      dataService.addItem(data.detail);
      setItems([...dataService.items]);
    };
    element.addEventListener('groceryAdded', handler);
    return () => element.removeEventListener('groceryAdded', handler);
  }, []);

  // groceryList
  let groceryList = useRef(null);
  useEffect(() => {
    // Set list
    const element = groceryList.current;
    element.items = items;

    // itemClicked handler
    let handler = data => {
      dataService.toggleItemStatus(data.detail[0]);
      setItems([...dataService.items]);
    };
    element.addEventListener('itemClicked', handler);
    return () => element.removeEventListener('itemClicked', handler);
  });

  return (
    <div className="App">
      <react-title text="Mixed Framework Groceries" />
      <div className="scrollable-area">
        <div className="add-grocery">
          <angular-add-grocery ref={addGrocery} />
        </div>
        <div className="grocery-list">
          <vue-wc-grocery-list ref={groceryList} />
        </div>
      </div>
    </div>
  );
}

export default App;
