// 01-sample-apps/react/src/GroceryList/GroceryList.js
import React from 'react';

import './GroceryList.css';

function GroceryList(props) {
  const handleItemClicked = item => {
    props.itemClicked(item.name);
  };

  return (
    <div className="GroceryList">
      {props.items && props.items.length > 0 ? (
        <div className="main-container">
          <h1>Groceries</h1>

          {props.items.map((item, index) => {
            return (
              <button
                key={item.name}
                className={`grocery-item ${
                  item.removed ? 'grocery-item--removed' : ''
                }`}
                onClick={() => handleItemClicked(item)}
              >
                <span className="grocery-item-count">{index + 1}.</span>
                <span>{item.name}</span>
              </button>
            );
          })}
        </div>
      ) : null}
    </div>
  );
}

export default GroceryList;

// 02-export-examples/angular/src/app/grocery-list/grocery-list.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

import { Item } from '../data.service';

@Component({
  selector: 'app-grocery-list',
  templateUrl: './grocery-list.component.html',
  styleUrls: ['./grocery-list.component.scss']
})
export class GroceryListComponent {
  @Input() items: Array<Item>;
  @Output() itemClicked: EventEmitter<string> = new EventEmitter();

  constructor() {}

  handleItemClicked(item: Item) {
    this.itemClicked.emit(item.name);
  }
}

<div *ngIf="items?.length > 0" class="main-container">
  <h1>Groceries</h1>
  <button
    *ngFor="let item of items; let i = index"
    class="grocery-item"
    [class.grocery-item--removed]="item.removed"
    (click)="handleItemClicked(item)"
  >
    <span class="grocery-item-count">{{ i + 1 }}.</span>
    <span>{{ item.name }}</span>
  </button>
</div>
