// 02-export-examples/react/src/App.js
import React, { useState } from 'react';

import './App.css';
import { DataService } from './data.service';
import Title from './Title/Title';
import AddGrocery from './AddGrocery/AddGrocery';
import GroceryList from './GroceryList/GroceryList';

const dataService = new DataService();

function App() {
  const [items, setItems] = useState(dataService.items);

  const groceryAdded = item => {
    dataService.addItem(item);
    setItems([...dataService.items]);
  };

  const groceryItemClicked = item => {
    dataService.toggleItemStatus(item);
    setItems([...dataService.items]);
  };

  return (
    <div className="App">
      <Title text="React Groceries" />
      <div className="scrollable-area">
        <div className="add-grocery">
          <AddGrocery addItem={groceryAdded} />
        </div>
        <div className="grocery-list">
          <GroceryList items={items} itemClicked={groceryItemClicked} />
        </div>
      </div>
    </div>
  );
}

export default App;

// 02-export-examples/angular/src/app/app.component.ts
import { Component } from '@angular/core';

import { DataService, Item } from './data.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  get groceryItems(): Array<Item> {
    return this.dataService.items;
  }

  constructor(private dataService: DataService) {}

  groceryAdded(name: string) {
    this.dataService.addItem(name);
  }

  groceryItemClicked(name: string) {
    this.dataService.toggleItemStatus(name);
  }

  clearItems() {
    this.dataService.clearItems();
  }
}
